## Neural Networks & Layers | Introduction to Deep Learning with PyTorch

A ***Neural Network (NNs)*** consists of **input**, **hidden**, and **output** layers, the input layer contains the *dataset features*, the output layer contains the *predictions*, and the hidden layers lie in between.

### *Our First Neural Network*

We will build a network with no hidden layers, where the output layer is a linear layer; every input neuron connects to every output neurons, referred to as a **fully connected layer**, this network is equivalent to a **linear network**

In [3]:
# Import torch as nn to avoid writing torch.nn -> torch.nn is used to build Neural Networks
import torch.nn as nn
import torch

# Create input_tensor with three features 
input_tensor = torch.tensor(
    [[0.3471, 0.4547, -0.2356]])

# Define linear layer
linear_layer = nn.Linear(
    in_features = 3, # Number of input features (which is 3 in this case)
    out_features = 2 # Number of output features (which is 2 in this case)
)

# Pass input through linear layer
output = linear_layer(input_tensor)
print(output) # Print the output of the linear layer

tensor([[0.4159, 0.3196]], grad_fn=<AddmmBackward0>)


When designing a neural network, the input and outer layer dimensions are predefined;

- the number of neurons in the input layer is the number of features in our dataset
- while the number of neurons in the output layer is the number of classes we want to predict

### Weights and Biases

When input tensor is passed through linear layer, a linear operation is performed to include weights and biases.

Each linear layer has a set of associated weights and biases, these are the key quantities that defines a neuron.

The **weights** reflects the importance of different features, while the **bias** is an additional term that is independent of the weights, providing the neuron with a baseline output.

At first, the linear layer assigns random weights and biases, these are tuned later on.

In [4]:
# weight
print(linear_layer.weight) # Print the weights of the linear layer

# bias
print(linear_layer.bias) # Print the bias of the linear layer

Parameter containing:
tensor([[ 0.2453,  0.1976, -0.1605],
        [ 0.0459, -0.4735,  0.2168]], requires_grad=True)
Parameter containing:
tensor([0.2031, 0.5701], requires_grad=True)


### A fully connected network in action

Say we have a weather dataset with three features, **temperature**, **humidity**, and **wind**. We want to predict whether it will rain or be cloudy.

- the **humidity** feature will have a more significant **weight** compared to the other features, as its a strong predictor of rain or clouds.
- the weather data is for a tropical region with a high probability of rain, so a **bias** is added to account for this baseline information.

With this information, our model makes a prediction.