### Using loss functions to assess model predictions 

We've generated predictions by running a forward pass, the next step is to see how good our predictions are compared to the actual values.

The ***loss function***, another component of **neural networks**, tells us how good our model is at making predictions during training.
- it takes a ***model prediction (ŷ)*** and ***true label or ground truth (y)*** as inputs and outputs a **float**

---

**Why do we need a loss function?**
> Let's use a multi-class classification model that predicts whether an animal is: a mammal (0), a bird (1), and a reptile (2).

Our dataset contains animal characteristics:
| Hair | Feathers | Eggs | Milk | Fins | Tail | Domestic | Catsize | Class |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | 
| 1 | 0 | 0 | 1 | 0 | 4 | 0 | 0 | 1 | 0 |

This example is a bear, therefore the **class** is zero [0] (mammal)
- If our model predicts that the class = 0 -> correct = ***low loss***
- If our model predicts class = 1 -> wrong = ***high loss***
- If our model predicts class = 1 -> wrong = ***high loss***

> Our goal is to **minimize loss**

---

**One-hot encoding concepts**
- loss is calculated by:
    - loss = F(y, ŷ) - takes in the ground truth (y) and the prediction (ŷ) as inputs and outputs
- y is a single integer (class label)
    - e.g y = 0 when y is a mammal
- ŷ is a tensor (raw prediction before softmax)
    - if N is the number of classes, e.g. N = 3, then ŷ is a tensor with N dimensions
        - e.g. ŷ = [-5.2, 4.6, 0.8]


We use **one-hot encoding** to convert an integer y to a tensor of zeros and ones, so we can compare to evaluate model performance.
> ground truth y = 0 | no. of classes N = 3

| Class | 0 | 1 | 2 |
|---|---:|---:|---:|
| One-hot encoding | 1 | 0 | 0 |


---



**Transforming labels with one-hot encoding**


In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F

print(F.one_hot(torch.tensor([0]), num_classes=3)) # ground truth y = 0
print(F.one_hot(torch.tensor([1]), num_classes=3)) # ground truth y = 1
print(F.one_hot(torch.tensor([2]), num_classes=3)) # ground truth y = 2

tensor([[1, 0, 0]])
tensor([[0, 1, 0]])
tensor([[0, 0, 1]])


**Cross entropy loss in PyTorch**
- With the encoding complete, we can pass it along with our predictions(ŷ) to a ***loss function***.

In [ ]:
from torch.nn import CrossEntropyLoss

scores = torch.tensor([-5.2, 4.6, 0.8]) # ŷ
one_hot_target = torch.tensor([1, 0, 0]) # ground truth y = 0

criterion = CrossEntropyLoss() # Most commonly used loss function for classification
print(criterion(scores.double(), one_hot_target.double()))

# the output is the computed loss value

tensor(9.8222, dtype=torch.float64)


### Bringing it all together
Loss function takes:
- **scores** - model predictions ***before*** the final softmax function
- **one_hot_target** - one hot encoded ground truth label

Loss function outputs:
- **loss** - a single **float**