# Deep Learning

## Introduction to Deep Learning with PyTorch

> **"Deep learning is everywhere!"**

Deep learning is used in many areas, including:

* Language translation
* Self-driving cars
* Medical diagnostics
* Chatbots

## What is Deep Learning?

Deep Learning is a **subset of Machine Learning** where the fundamental model structure consists of:

**Inputs → Hidden Layers → Outputs**

A neural network can have **one or many hidden layers**.

The original intuition behind deep learning was to create models inspired by how the **human brain** works, through interconnected cells called **neurons**. This is why we continue to call deep learning models **neural networks**.

These models require large amounts of data, with at least **100,000 data points**.

## PyTorch

This course will focus on one specific deep learning framework: **PyTorch**, one of the most popular deep learning frameworks. It was originally developed by **Meta AI** and is now part of the **Linux Foundation**.

### Tensors

The fundamental data structure in PyTorch is the **Tensor**, which is similar to an array or matrix.

Tensors can support many mathematical operations and form the **building blocks of neural networks**.

---

### Tensor Attributes

In [ ]:
import torch # Imports the PyTorch library, which is used for tensor computations and deep learning.

In [ ]:
my_list = [[1, 2, 3], [4, 5, 6]] # Creates a nested list (a list of lists) with two sublists.
tensor = torch.tensor(my_list) # Converts the nested list into a PyTorch tensor, which is a multi-dimensional array.
print(tensor) # Prints the tensor to the console, displaying its contents.

# The output will be:
# tensor([[1, 2, 3],
#        [4, 5, 6]])
# This class converts the data into a compatible format for Deep Learning

tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
my_list = [[1, 2, 3], [4, 5, 6]] 
tensor = torch.tensor(my_list)
print(tensor.shape) # Displays the shape of our tensor
print(tensor.dtype) # Displays the data type of our tensor

torch.Size([2, 3])
torch.int64


### Tensor Operations

- PyTorch tensors can be added or subtracted, provided that their shapes are compatible.

Two tensors are compatible if they have the same shape, meaning their ***dimensions*** align exactly.

In [4]:
# Compatible Shapes

a = torch.tensor([[1, 1],
                  [2, 2]])

b = torch.tensor([[2, 2],
                  [3, 3]])

print(a + b) # Performs element-wise addition of tensors a and b

tensor([[3, 3],
        [5, 5]])


In [ ]:
# Incompatible Shapes

a = torch.tensor([[1, 1],
                  [2, 2]])

c = torch.tensor([[2, 2, 2],
                  [3, 3, 3]])

print (a + c) # This will raise an error because the shapes of tensors a and c are not compatible for addition.

### Element-wise Multiplication

In [6]:
a = torch.tensor([[1, 1],
                  [2, 2]])
b = torch.tensor([[2, 2],
                  [3, 3]])

print(a * b) # Performs element-wise multiplication of tensors a and b

tensor([[2, 2],
        [6, 6]])


### Matrix Multiplication

- a way of combining two matrices to make a new one.

each value in the new matrix comes from multiplying a row from the first matrix, with a column from the second matrix and summing the results.

In [7]:
a = torch.tensor([[1, 1],
                  [2, 2]])
b = torch.tensor([[2, 2],
                  [3, 3]])

print(a @ b) # Performs matrix multiplication of tensors a and b

tensor([[ 5,  5],
        [10, 10]])
