### **A Deeper Dive Into Loading Data**

Efficient data handling is key to training deep learning models.

In [1]:
import pandas as pd

animals = pd.read_csv('../data/animal_dataset.csv') # Our animal classification data is in a CSV file

| animal_name | hair | feathers | eggs | milk | predator | legs | tail | type |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| sparrow | 0 | 1 | 1 | 0 | 0 | 2 | 1 | 0 |
| eagle | 0 | 1 | 1 | 0 | 0 | 2 | 1 | 0 |
| cat | 1 | 0 | 0 | 1 | 1 | 4 | 1 | 1 |
| dog | 1 | 0 | 0 | 1 | 0 | 4 | 1 | 1 |
| lizard | 0 | 0 | 1 | 0 | 1 | 4 | 1 | 2 |


> Type Categories: bird (0), mammal (1), reptile (2)

In [5]:
import numpy as np

# Define input features
features = animals.iloc[:, 1:-1] 

X = features.to_numpy()
print("Input features:")
print(X)


# Define target values (ground truth)
target = animals.iloc[:, -1]
y = target.to_numpy()
print("\nTarget values:")
print(y)

Input features:
[[0 1 1 0 0 2 1]
 [0 1 1 0 0 2 1]
 [1 0 0 1 1 4 1]
 [1 0 0 1 0 4 1]
 [0 0 1 0 1 4 1]]

Target values:
[0 0 1 1 2]


The ***.iloc()*** function lets us select all features **EXCEPT** the first (*animal_name*) and the last (*type*) giving us our input features.

The input features are then converted into a numpy array (X) for easier handling with PyTorch.

Similarly, we can extract the **LAST** column (*type*), and store it as an array of our target values, which represents the class labels of each animal, (y).

---

In [6]:
# We will use TensorDataset to prepare data for PyTorch models.

import torch
from torch.utils.data import TensorDataset # This allows us to store our fetaures (X) and target values (y) in tensors, making them easy to manage.

# Instantiate dataset class
dataset = TensorDataset(torch.tensor(X), torch.tensor(y))

# Acces an individual sample
input_sample, label_sample = dataset[0]
print("Input sample:", input_sample)
print("Label sample:", label_sample)

Input sample: tensor([0, 1, 1, 0, 0, 2, 1])
Label sample: tensor(0)


**DataLoader**

Once we've created our dataset using TensorDataset, we can pass it to DataLoader, to efficiently manage data loading during training.

1. batch_size - Determines how many samples are included in each iteration. Batching helps process multiple samples at once, making it more efficient.
2. shuffle - randomized the data order at each epoch, helping improve model generalization
    - Epoch - one full pass through the training dataloader.
    - Generalization - the model performs well with unseen data, rather than just memorizing the training set.


In [7]:
from torch.utils.data import DataLoader

batch_size = 2 
shuffle = True

# Create a DataLoader
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

In [8]:
# Iterate over the dataloader
for batch_inputs, batch_labels in dataloader:
    print("Batch inputs:", batch_inputs)
    print("Batch labels:", batch_labels)

Batch inputs: tensor([[1, 0, 0, 1, 1, 4, 1],
        [0, 1, 1, 0, 0, 2, 1]])
Batch labels: tensor([1, 0])
Batch inputs: tensor([[0, 1, 1, 0, 0, 2, 1],
        [1, 0, 0, 1, 0, 4, 1]])
Batch labels: tensor([0, 1])
Batch inputs: tensor([[0, 0, 1, 0, 1, 4, 1]])
Batch labels: tensor([2])
